// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxqW8g3_-1XTWV83SNGfyRDZPsGb0R1Zc',
    appId: '1:959040821101:web:bd61699d560b32be5a6c64',
    messagingSenderId: '959040821101',
    projectId: 'mind-well-fb255',
    authDomain: 'mind-well-fb255.firebaseapp.com',
    storageBucket: 'mind-well-fb255.appspot.com',
    measurementId: 'G-QD4H7JJZHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy91zBaOK3qwWHiR9MYhOdBraW2APkQZ4',
    appId: '1:959040821101:android:7f8e9e2b655033da5a6c64',
    messagingSenderId: '959040821101',
    projectId: 'mind-well-fb255',
    storageBucket: 'mind-well-fb255.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDypd-y5hnDRSPXfxurbElbgZ829IhK4C8',
    appId: '1:959040821101:ios:dac6e6dd10f83f355a6c64',
    messagingSenderId: '959040821101',
    projectId: 'mind-well-fb255',
    storageBucket: 'mind-well-fb255.appspot.com',
    iosBundleId: 'com.example.mindWell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDypd-y5hnDRSPXfxurbElbgZ829IhK4C8',
    appId: '1:959040821101:ios:1df4a6c9fb4fe0365a6c64',
    messagingSenderId: '959040821101',
    projectId: 'mind-well-fb255',
    storageBucket: 'mind-well-fb255.appspot.com',
    iosBundleId: 'com.example.mindWell.RunnerTests',
  );
}
